# Generated by Django 5.1.1 on 2024-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_carbrandmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
