# Generated by Django 5.1.1 on 2024-12-18 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('car_app', '0004_alter_carmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.carbrandmodel'),
        ),
        migrations.DeleteModel(
            name='CarBrandModel',
        ),
    ]
